version: '3'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - net-case-itau

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    networks:
      - net-case-itau
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    networks:
      - net-case-itau
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - net-case-itau
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  customer-api:
    build: 
      context: './app-customer'
      dockerfile: 'Dockerfile-maven'
    container_name: customer-api
    ports:
      - 8081:8081
    environment:
      MONGODB_HOST: mongo
    networks:
      - net-case-itau
    depends_on:
      - mongo

  notification-api:
    build: 
      context: './app-notification'
      dockerfile: 'Dockerfile-maven'
    container_name: notification-api
    ports:
      - 8082:8082
    environment:
      MONGODB_HOST: mongo
      KAFKA_HOST: kafka
      CUSTOMER_API_HOST: customer-api
    networks:
      - net-case-itau
    depends_on:
      - mongo
      - kafka
      - customer-api

  catalog-api:
    build: 
      context: './app-catalog'
      dockerfile: 'Dockerfile-maven'
    container_name: catalog-api
    ports:
      - 8083:8083
    environment:
      MONGODB_HOST: mongo
    networks:
      - net-case-itau
    depends_on:
      - mongo

  debt-api:
    build: 
      context: './app-debt'
      dockerfile: 'Dockerfile-maven'
    container_name: debt-api
    ports:
      - 8084:8084
    environment:
      MONGODB_HOST: mongo
      KAFKA_HOST: kafka
    networks:
      - net-case-itau
    depends_on:
      - mongo
      - kafka

  payment-api:
    build: 
      context: './app-payment'
      dockerfile: 'Dockerfile-maven'
    container_name: payment-api
    ports:
      - 8085:8085
    environment:
      MONGODB_HOST: mongo
      KAFKA_HOST: kafka
      CATALOG_API_HOST: catalog-api
    networks:
      - net-case-itau
    depends_on:
      - mongo
      - kafka
      - catalog-api

networks:
  net-case-itau:
    driver: bridge
