
server:
  port: 8085

springdoc:
  swagger-ui:
    operationsSorter: method

spring:
  data:
    mongodb:
      username: payment
      password: payment
      host: localhost
      port: 27017
      database: dbPayment
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: payment-group
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      payment-renegotiation-request: payment.renegotiation.create.request