server:
  port: 8081

springdoc:
  swagger-ui:
    operationsSorter: method

spring:
  data:
    mongodb:
      username: customer
      password: customer
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: dbCustomer
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}
