server:
  port: 8082

spring:
  data:
    mongodb:
      username: notification
      password: notification
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: dbNotification
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}
  kafka:
    consumer:
      bootstrap-servers:
        - ${KAFKA_HOST:localhost}:9092
      group-id: notification-group
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      concurrency: 2
    topics:
      notification-request: notifications.customer.request

feign:
  customer:
    name: customerClient
    url: http://${CUSTOMER_API_HOST:localhost}:8081

#Resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 50
        failureRateThreshold: 40
        minimumNumberOfCalls: 5
        ignoreExceptions:
          - feign.FeignException.FeignClientException
    instances:
      customerClient:
        baseConfig: default